#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long N;
	std::scanf("%lld", &N);
	vector<string> S, T;
	string Stmp, Ttmp;
	for (int i = 0; i < N; i++)
	{
		cin >> Stmp >> Ttmp;
		S.push_back(Stmp);
		T.push_back(Ttmp);
	}

	for (int i = 0; i < N; i++)
	{
		// cout << S[i] << ", " << T[i] << endl;
		for (int j = i + 1; j < N; j++)
		{
			if (S[i] + "+" + T[i] == S[j] + "+" + T[j])
			{
				cout << YES << endl;
				return 0;
			}
		}
	}
	cout << NO << endl;
	return 0;
}
