#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

const string YES = "Yes";
const string NO = "No";

void solve(long long H, long long W, std::vector<std::vector<long long>> A)
{
	for (int i = 0; i < H - 1; i++)
	{
		for (int i2 = i + 1; i2 < H; i2++)
		{
			for (int j = 0; j < W - 1; j++)
			{
				for (int j2 = j + 1; j2 < W; j2++)
				{
					// cout << "(" << i + 1 << ", " << i2 + 1 << ", " << j + 1 << ", " << j2 + 1 << ")" << endl;
					if (A[i][j] + A[i2][j2] > A[i2][j] + A[i][j2])
					{
						cout << NO << endl;
						return;
					}
				}
			}
		}
	}
	cout << YES << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long H;
	std::scanf("%lld", &H);
	long long W;
	std::scanf("%lld", &W);
	std::vector<std::vector<long long>> A(H, std::vector<long long>(W));
	for (int i = 0; i < H; i++)
	{
		for (int j = 0; j < W; j++)
		{
			std::scanf("%lld", &A[i][j]);
		}
	}
	solve(H, W, std::move(A));
	return 0;
}
