#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	// Failed to predict input format
	long long N;
	std::scanf("%lld", &N);

	ll L[N];
	vector<std::vector<long long>> a;
	for (int i = 0; i < N; i++)
	{
		std::scanf("%lld", &L[i]);
		vector<ll> vectmp;
		a.push_back(vectmp);
		for (int j = 0; j < L[i]; j++)
		{
			ll atmp;
			cin >> atmp;
			a[i].push_back(atmp);
		}
	}

	// for (int i = 0; i < N; i++)
	// {
	// 	cout << L[i] << " ";
	// 	for (int j = 0; j < L[i]; j++)
	// 	{
	// 		cout << a[i][j] << " ";
	// 	}
	// 	cout << endl;
	// }
	ll ans = 0;
	std::sort(a.begin(), a.end());
	a.erase(std::unique(a.begin(), a.end()), a.end());
	for (auto it = a.begin(); it != a.end(); ++it)
	{
		// std::cout << it << " ";
		ans++;
	}
	cout << ans << endl;
	return 0;
}
