#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

// Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	double A;
	string ans = "";
	cin >> A;

	int X = A;
	int Y = (A - X) * 10;

	if (0 <= Y && Y <= 2)
	{
		ans = "-";
	}
	else if (7 <= Y && Y <= 9)
	{
		ans = "+";
	}
	cout << X << ans << endl;
	return 0;
}
