#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long N, map<string, int> S)
{
	string ans_name;
	ll ans_value = 0;
	for (const auto &[key, value] : S)
	{
		// std::cout << key << " => " << value << "\n";
		if (ans_value < value)
		{
			ans_name = key;
			ans_value = value;
		}
	}
	cout << ans_name << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long N;
	std::scanf("%lld", &N);
	map<string, int> S;
	string tmp;
	for (int i = 0; i < N; i++)
	{
		std::cin >> tmp;
		S[tmp] += 1;
	}
	solve(N, std::move(S));
	return 0;
}
