#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long P)
{
    ll i = 1, fac = 1, cnt = 0;
    while (true)
    {
        i++;
        fac = fac * i;
        if (P < fac)
        {
            break;
        }
    }

    // cout << i << "," << fac << endl;

    while (true)
    {
        if (i != 0)
        {
            fac = fac / i;
        }

        i--;
        while (true)
        {
            if (P < fac)
            {
                goto end;
            }
            P -= fac;
            // cout << i << ',' << fac << "," << P << endl;
            cnt++;
            if (P < fac)
            {
                goto end;
            }
        }
    end:

        if (P <= 0)
        {
            cout << cnt << endl;
            return;
        }
    }
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long P;
    std::scanf("%lld", &P);
    solve(P);
    return 0;
}
