#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long Q;
    std::scanf("%lld", &Q);

    priority_queue<ll, vector<ll>, greater<ll>> q;
    int queue_num;
    ll sum = 0;
    for (int i = 0; i < Q; i++)
    {
        cin >> queue_num;
        if (queue_num == 3)
        {
            ll ans = q.top() + sum;
            q.pop();
            cout << ans << endl;
        }
        else
        {
            ll x;
            cin >> x;
            if (queue_num == 1)
            {
                q.push(x - sum);
            }
            else
            {
                sum += x;
            }
        }
    }

    return 0;
}
