#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long A, long long B, long long C, long long D)
{
	if (B >= C * D)
	{
		cout << -1 << endl;
		return;
	}

	int i = 0;
	while (true)
	{
		if (A + B * i <= C * i * D)
		{
			cout << i << endl;
			break;
		}
		i++;
	}
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long A;
	std::scanf("%lld", &A);
	long long B;
	std::scanf("%lld", &B);
	long long C;
	std::scanf("%lld", &C);
	long long D;
	std::scanf("%lld", &D);
	solve(A, B, C, D);
	return 0;
}
