#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long A, long long B, long long C)
{
	ll ans = 0;
	while (ans <= B)
	{
		ans += C;
		if (A <= ans && ans <= B)
		{
			cout << ans << endl;
			return;
		}
	}
	cout << -1 << endl;
}

// Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long A;
	std::scanf("%lld", &A);
	long long B;
	std::scanf("%lld", &B);
	long long C;
	std::scanf("%lld", &C);
	solve(A, B, C);
	return 0;
}
