#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long K, string A, string B)
{
	ll Anum = 0, Bnum = 0;
	for (int i = 0; i < A.length(); i++)
	{
		Anum += pow(K, (A.length() - i - 1)) * (A[i] - '0');
	}
	for (int i = 0; i < B.length(); i++)
	{
		Bnum += pow(K, (B.length() - i - 1)) * (B[i] - '0');
	}
	cout << Anum * Bnum << endl;
}

// Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long K;
	std::scanf("%lld", &K);
	string A;
	std::cin >> A;
	string B;
	std::cin >> B;
	solve(K, A, B);
	return 0;
}
