#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

const string YES = "Yes";
const string NO = "No";

void solve(long long N, std::vector<long long> a, std::vector<long long> b)
{
	ll target;
	if (a[0] == a[1] || a[0] == b[1])
	{
		target = a[0];
	}
	else if (b[0] == a[1] || b[0] == b[1])
	{
		target = b[0];
	}
	else
	{
		cout << NO << endl;
		return;
	}
	for (int i = 2; i < N - 1; i++)
	{
		if (a[i] != target && b[i] != target)
		{
			cout << NO << endl;
			return;
		}
	}
	cout << YES << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long N;
	std::scanf("%lld", &N);
	std::vector<long long> a(N - 1);
	std::vector<long long> b(N - 1);
	for (int i = 0; i < N - 1; i++)
	{
		std::scanf("%lld", &a[i]);
		std::scanf("%lld", &b[i]);
	}
	solve(N, std::move(a), std::move(b));
	return 0;
}
