#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(std::string S)
{
	vector<string> shifts;
	for (int i = 0; i < S.length(); i++)
	{
		string tmp_shifts = "";
		tmp_shifts = S.substr(i);
		tmp_shifts += S.substr(0, i);
		shifts.push_back(tmp_shifts);
	}

	sort(shifts.begin(), shifts.end());

	// for (int i = 0; i < S.length(); i++)
	// {
	// 	cout << shifts[i] << endl;
	// }
	cout << shifts[0] << endl;
	cout << shifts[S.length() - 1] << endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	std::string S;
	std::cin >> S;
	solve(S);
	return 0;
}
