#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

bool judge(string S)
{
    int dep = 0;
    for (int i = 0; i < S.size(); i++)
    {
        if (S[i] == '(')
        {
            dep += 1;
        }

        if (S[i] == ')')
        {
            dep -= 1;
        }
        if (dep < 0)
        {
            return false;
        }
    }
    if (dep == 0)
    {
        return true;
    }

    return false;
}

void solve(long long N)
{
    bool flg = false;
    for (int i = 0; i < pow(2, N); i++)
    {
        string Candidate = "";
        for (int j = N - 1; j >= 0; j--)
        {
            if ((i & (1 << j)) == 0)
            {
                Candidate += "(";
            }
            else
            {
                Candidate += ")";
            }
        }
        if (judge(Candidate))
        {
            cout << Candidate << endl;
            flg = true;
        }
    }
    if (!flg)
    {
        cout << endl;
    }
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    std::scanf("%lld", &N);
    solve(N);
    return 0;
}
