#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;


void solve(long long T, long long L, long long X, long long Y, long long Q, std::vector<long long> E){

}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long T;
    std::scanf("%lld", &T);
    long long L;
    std::scanf("%lld", &L);
    long long X;
    std::scanf("%lld", &X);
    long long Y;
    std::scanf("%lld", &Y);
    long long Q;
    std::scanf("%lld", &Q);
    std::vector<long long> E(Q);
    for(int i = 0 ; i < Q ; i++){
        std::scanf("%lld", &E[i]);
    }
    solve(T, L, X, Y, Q, std::move(E));
    return 0;
}
