#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;


void solve(long long N, std::vector<long long> lx, std::vector<long long> ly, std::vector<long long> rx, std::vector<long long> ry){

}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> lx(N);
    std::vector<long long> ly(N);
    std::vector<long long> rx(N);
    std::vector<long long> ry(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &lx[i]);
        std::scanf("%lld", &ly[i]);
        std::scanf("%lld", &rx[i]);
        std::scanf("%lld", &ry[i]);
    }
    solve(N, std::move(lx), std::move(ly), std::move(rx), std::move(ry));
    return 0;
}
