#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

const string YES = "Yes";
const string NO = "No";

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	// Failed to predict input format
	long long N, M;
	std::scanf("%lld %lld", &N, &M);
	ll B[N][M];
	for (int i = 0; i < N; i++)
	{
		for (int j = 0; j < M; j++)
		{
			std::scanf("%lld", &B[i][j]);
		}
	}

	// for (int i = 0; i < N; i++)
	// {
	// 	for (int j = 0; j < M; j++)
	// 	{
	// 		cout << B[i][j] << " ";
	// 	}
	// 	cout << endl;
	// }

	// ll rowSum[N];
	for (int i = 0; i < N; i++)
	{
		// rowSum[i] = 0;
		for (int j = 0; j < M; j++)
		{
			if (j != 0)
			{
				if ((B[i][j] - 1) % 7 != ((B[i][j - 1] - 1) % 7) + 1)
				{
					cout << NO << endl;
					return 0;
				}
			}
			if (i != 0)
			{
				if (B[i][j] != B[i - 1][j] + 7)
				{
					cout << NO << endl;
					return 0;
				}
			}
			// rowSum[i] += B[i][j];
		}
		// if (i != 0)
		// {
		// 	if (rowSum[i] != rowSum[i - 1] + 7 * M)
		// 	{
		// 		// cout << rowSum[i] << " " << rowSum[i - 1] << endl;
		// 		cout << NO << endl;
		// 		return 0;
		// 	}
		// }
	}

	cout << YES << endl;
	return 0;
}
