#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(std::vector<std::string> S)
{
	std::vector<std::string> A = {"ABC", "ARC", "AHC", "AGC"};

	for (int i = 0; i < A.size(); i++)
	{
		auto result = std::find(S.begin(), S.end(), A[i]);
		if (result == S.end())
		{
			cout << A[i] << endl;
			return;
		}
	}
}

// Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	std::vector<std::string> S(3);
	for (int i = 0; i < 3; i++)
	{
		std::cin >> S[i];
	}
	solve(std::move(S));
	return 0;
}
