#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long x, long long y)
{
    if (x == y)
    {
        cout << x << endl;
    }
    else
    {
        if (x + y == 1)
        {
            cout << 2 << endl;
        }
        else if (x + y == 3)
        {
            cout << 0 << endl;
        }
        else
        {
            cout << 1 << endl;
        }
    }
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long x;
    std::scanf("%lld", &x);
    long long y;
    std::scanf("%lld", &y);
    solve(x, y);
    return 0;
}
