// https://atcoder.jp/contests/arc122/submissions/23364770
#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <cstring>
using namespace std;
typedef long long ll;

const long long MOD = 1000000007;

void solve(long long N, std::vector<long long> A)
{
	ll dp[100010][2] = {}, way[100010][2] = {};

	way[1][0] = 1;
	dp[1][0] = A[0];

	for (int i = 1; i < N; i++)
	{
		dp[i + 1][0] = dp[i][0] + A[i] * way[i][0] + dp[i][1] + A[i] * way[i][1];
		dp[i + 1][1] = dp[i][0] - A[i] * way[i][0];
		way[i + 1][0] = way[i][0] + way[i][1];
		way[i + 1][1] = way[i][0];

		dp[i + 1][0] %= MOD;
		dp[i + 1][1] %= MOD;
		way[i + 1][0] %= MOD;
		way[i + 1][1] %= MOD;
	}
	cout << (dp[N][0] + dp[N][1] + MOD) % MOD << endl;
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long N;
	std::scanf("%lld", &N);
	std::vector<long long> A(N);
	for (int i = 0; i < N; i++)
	{
		std::scanf("%lld", &A[i]);
	}
	solve(N, std::move(A));
	return 0;
}
