#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long H, long long W)
{
    ll ans;
    if (H == 1 || W == 1)
    {
        ans = H * W;
    }
    else
    {
        ans = ceil(((double)H / 2)) * ceil(((double)W / 2));
    }

    cout << ans << endl;
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long H;
    std::scanf("%lld", &H);
    long long W;
    std::scanf("%lld", &W);
    solve(H, W);
    return 0;
}
