#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

const string YES = "Yes";
const string NO = "No";

void solve(long long N, long long X, std::vector<long long> A)
{
	ll cnt = 0;
	for (int i = 0; i < N; i++)
	{

		cnt += A[i];
		if (i % 2 != 0)
		{
			cnt--;
		}
	}

	if (X >= cnt)
	{
		cout << YES << endl;
	}
	else
	{
		cout << NO << endl;
	}
}

// Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long N;
	std::scanf("%lld", &N);
	long long X;
	std::scanf("%lld", &X);
	std::vector<long long> A(N);
	for (int i = 0; i < N; i++)
	{
		std::scanf("%lld", &A[i]);
	}
	solve(N, X, std::move(A));
	return 0;
}
