#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long A, long long B, long long C)
{
	if (A >= 0 && B >= 0)
	{
		if (A == B)
		{
			cout << "=" << endl;
		}
		else if (A > B)
		{
			cout << ">" << endl;
		}
		else
		{
			cout << "<" << endl;
		}
	}
	else if (A < 0 && B < 0)
	{
		if (A == B)
		{
			cout << "=" << endl;
		}
		else if (A > B)
		{
			if (C % 2 == 0)
			{
				cout << "<" << endl;
			}
			else
			{
				cout << ">" << endl;
			}
		}
		else
		{
			if (C % 2 == 0)
			{
				cout << ">" << endl;
			}
			else
			{
				cout << "<" << endl;
			}
		}
	}
	else
	{
		if (abs(A) == abs(B))
		{
			if (C % 2 == 0)
			{
				cout << "=" << endl;
			}
			else
			{
				if (A < B)
				{
					cout << "<" << endl;
				}
				else
				{
					cout << ">" << endl;
				}
			}
		}
		else if (A < B)
		{
			// Aが負、Bが正
			if (abs(A) < abs(B))
			{
				cout << "<" << endl;
			}
			else
			{
				if (C % 2 == 0)
				{
					cout << ">" << endl;
				}
				else
				{
					cout << "<" << endl;
				}
			}
		}
		else
		{
			// Aが正、Bが負
			if (abs(A) < abs(B))
			{
				if (C % 2 == 0)
				{
					cout << "<" << endl;
				}
				else
				{
					cout << ">" << endl;
				}
			}
			else
			{
				cout << ">" << endl;
			}
		}
	}
}

// Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long A;
	std::scanf("%lld", &A);
	long long B;
	std::scanf("%lld", &B);
	long long C;
	std::scanf("%lld", &C);
	solve(A, B, C);
	return 0;
}
