#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

ll q[200001];

void solve(long long N, std::vector<long long> p)
{
	for (int i = 0; i < N; i++)
	{
		q[p[i] - 1] = i + 1;
	}

	for (int i = 0; i < N; i++)
	{
		cout << q[i];
		if (i != N - 1)
		{
			cout << " ";
		}
	}

	cout << endl;
}

// Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
	long long N;
	std::scanf("%lld", &N);
	std::vector<long long> p(N);
	for (int i = 0; i < N; i++)
	{
		std::scanf("%lld", &p[i]);
	}
	solve(N, std::move(p));
	return 0;
}
