#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;
typedef long long ll;

void solve(long long S, long long T)
{
    int a, b, c;
    ll cnt = 0;
    for (a = 0; a <= S; a++)
    {
        for (b = 0; a + b <= S; b++)
        {
            for (c = 0; a + b + c <= S; c++)
            {
                if (a * b * c <= T)
                {
                    cnt++;
                }
            }
        }
    }
    cout << cnt << endl;
}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long S;
    std::scanf("%lld", &S);
    long long T;
    std::scanf("%lld", &T);
    solve(S, T);
    return 0;
}
